SELECT (
    CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT)
) AS FILE_PATH
FROM 
(
    SELECT *
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) O LEFT JOIN USED_GOODS_FILE F ON O.BOARD_ID = F.BOARD_ID
ORDER BY FILE_PATH DESC