SELECT CATEGORY, SUM(S.TOTAL) AS TOTAL_SALES
FROM BOOK B LEFT JOIN 
(
    SELECT BOOK_ID, SUM(SALES) AS TOTAL
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01-%'
    GROUP BY BOOK_ID
) AS S ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY